name: GitLab Runner
version: "1.0.1"
slug: gitlab-runner-ha-addon
description: "GitLab Runner for Home Assistant Supervisor."
url: "https://docs.gitlab.com/runner/"
startup: services
boot: auto
arch:
  - amd64
  - armv7
  - aarch64
map_data: true
map_config: false
cap_add:
  - SYS_ADMIN
  - NET_ADMIN
security_opt:
  - apparmor=unconfined
options:
  registration_token: ""
  gitlab_url: "https://gitlab.com/"
  runner_tags: "ha"
  executor: "shell"
  docker_image: "alpine:latest"
schema:
  registration_token: str
  gitlab_url: str
  runner_tags: str
  executor: str
  docker_image: str
ports: {}
